# CMake generated Testfile for 
# Source directory: C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/opencv
# Build directory: C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/build_js
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("3rdparty/zlib")
subdirs("3rdparty/harfbuzz")
subdirs("3rdparty/protobuf")
subdirs("include")
subdirs("modules/.firstpass/calib")
subdirs("modules/.firstpass/core")
subdirs("modules/.firstpass/dnn")
subdirs("modules/.firstpass/features")
subdirs("modules/.firstpass/flann")
subdirs("modules/.firstpass/geometry")
subdirs("modules/.firstpass/highgui")
subdirs("modules/.firstpass/imgcodecs")
subdirs("modules/.firstpass/imgproc")
subdirs("modules/.firstpass/java")
subdirs("modules/.firstpass/js")
subdirs("modules/.firstpass/objc")
subdirs("modules/.firstpass/objdetect")
subdirs("modules/.firstpass/photo")
subdirs("modules/.firstpass/ptcloud")
subdirs("modules/.firstpass/python")
subdirs("modules/.firstpass/stereo")
subdirs("modules/.firstpass/stitching")
subdirs("modules/.firstpass/ts")
subdirs("modules/.firstpass/video")
subdirs("modules/.firstpass/videoio")
subdirs("modules/.firstpass/world")
subdirs("modules/core")
subdirs("modules/flann")
subdirs("modules/geometry")
subdirs("modules/imgproc")
subdirs("modules/photo")
subdirs("modules/python_tests")
subdirs("modules/stereo")
subdirs("modules/dnn")
subdirs("modules/features")
subdirs("modules/objdetect")
subdirs("modules/video")
subdirs("modules/calib")
subdirs("modules/java_bindings_generator")
subdirs("modules/js_bindings_generator")
subdirs("modules/objc_bindings_generator")
subdirs("modules/python_bindings_generator")
subdirs("modules/js")
subdirs("doc")
subdirs("docs_sphinx")
subdirs("samples")
