//user-defined headers
#include "C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/opencv/modules/core/misc/python/pyopencv_async.hpp"
#include "C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/opencv/modules/core/misc/python/pyopencv_core.hpp"
#include "C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/opencv/modules/core/misc/python/pyopencv_cuda.hpp"
#include "C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/opencv/modules/core/misc/python/pyopencv_umat.hpp"
#include "C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/opencv/modules/flann/misc/python/pyopencv_flann.hpp"
#include "C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/opencv/modules/dnn/misc/python/pyopencv_dnn.hpp"
#include "C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/opencv/modules/features/misc/python/pyopencv_features.hpp"
#include "C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/opencv/modules/objdetect/misc/python/pyopencv_objdetect.hpp"
#include "C:/Users/LEGION/Desktop/MedLens Vision/opencv5-build/opencv/modules/video/misc/python/pyopencv_video.hpp"
